### ISSUE TITLE
Test issue from vscode

### ISSUE THREAD

**Issue by ant358** [Eric-Lingren/oanda_v20_platform_public#1]
https://github.com/ant358/oanda_v20_platform_public/blob/bde19155ed94c68ec6421438aad6b18bc2228e1b/main.py#L22-L22

**Comment by ant358** [comment]
Sorry, no issue it was supposed to end up in my fork of your repo :-) 
Thanks for making the Oanda platform public. I am enjoying using it more than other methods that I have tried out.

**Comment by Eric-Lingren** [comment]
No problem!  I'm glad you are enjoying this repo.  I have 2 versions of it..  One I actively work on privately, and my published version which you found.  I have been spending the last while building a back tester that will integrate the same strategies seamlessly between backtesting and live trading within this same ecosystem.  This is getting pretty close to being done and should be updated into the public repo within the next few weeks.  It will work in conjunction with my dukascopy data scraper repo here:  https://github.com/Eric-Lingren/duka

Sorry there are not instructions on that one.  I'm happy to write them up and notify you when that as well as the back tester is live if you have interest in that.  

I also have an ubuntu deployment library that works in conjunction with this repo if you have interest in playing with it on a live server:  https://github.com/Eric-Lingren/oanda_server_scripts

This is more of a hobby project for me to fill my own needs, but if you have ideas, let me know!  If you get stuck with anything or there are ways I can improve my user docs, lmk about that as well.  

I've only been writing in python for about a year, so there are probably ways to improve some of the code flow.  I don't think my class extensibility is particularly good, but it seems to work...

**Comment by ant358** [comment]
No worries, It's a hobby project for me as well. I have another oanda project that I stopped working on probably six months ago based on hootnot's oanda-api-v20. I got most of the data I needed for analysis from that one but was struggling to get it trading the way I wanted it to.  I found that I understood how your platform worked quickly and it made logical sense to me. So, I will try and get my data analysis code to integrate. I made a few changes to my fork to get it trading from the IDE so I can play around with the code interactively and see what happens. It all worked pretty well and the basic RSI strategy traded away happily. I work with python most days for data science but I am new to collaborating on github. Hopefully, I won't send too many more accidental issues through to you! I found the setting to enable them on the fork. Eventually, the plan is to put the code up on a server and I will check out your server scripts. Then maybe one day the trading profits will roll in :-)

**Comment by Eric-Lingren** [comment]
I totally understand.  We'll have fun playing with it and use it to your hearts content! I hope you can get your strategies implemented!  If you have questions feel free to ask.

I had that same issue with some other platforms that I tried working with. Professionally I'm a Node.js engineer so I figured there no point using all these 3rd party package plugins when Oanda has clean API documentation.  So I set out to build an API-based platform that I can quickly swap out the request endpoints or the json object structure whenever oanda updates their versions, so it doesn't rely on anything other than making raw HTTP rest requests for data and orders.

Theres still a lot more that can be included and its quite rudimentary right now (market order only - no trailing stops, no scaling in and out of positions, etc), but I hope its a good framework to scale those options in down the road as my strategies become more complex.

I'm glad the code is easy to understand!  That means a lot coming from a data scientist :) Hope you start making some money!
